### ISSUE TITLE
Allow for dynamic prefix

### ISSUE THREAD

**Issue by Dartv** [hkwu/ghastly#3]
So the bot can use different prefix for different guilds.
If you define prefix as `!` or something similar, there is a good chance it will clash with other bots.

Maybe opt it to be a function that receives context and returns string?

```js
new Client({
  prefix: async ({ message: { guild: { id } } }) => (await Guilds.findOne({ id })).prefix,
});
```

**Comment by hkwu** [comment]
I think something like that would be a good addition to add more flexibility to the prefix system. Instead of returning a string though, it would get the message and return a bool indicating if the message passes the prefix. That way you could add any sort of custom prefix logic you need (and it will work with regex too).

**Comment by hkwu** [comment]
So I ended up with this system:

```js
new Client({
  // function
  prefix: ({ content, guild: { id } }) => (
    (new RegExp((await Guilds.findOne({ id })).prefix)).test(content)
  ),

  // optionally async
  prefix: async ({ content, guild: { id } }) => (
    (new RegExp((await Guilds.findOne({ id })).prefix)).test(content)
  ),

  // RegExp
  prefix: /jarvis,/i,
});
```

Need to see if the RegExp implementation is as easy as I think it is, but the function based prefix works well.

**Comment by Dartv** [comment]
Seems good. It's not a problem for me, but why not allow for a string if you're scared of adding more complexity?

**Comment by hkwu** [comment]
It would be a bit more complex to let the function return a string, since I have to go through the extra step of rebuilding the prefix for every message, versus just having it built when the client is instantiated.

Can you think of any use cases that my system wouldn't cover versus the original? (I fixed the previous comment, the function actually receives the message only, not the context.)

**Comment by Dartv** [comment]
No, I think your implementation is perfectly fine.

**Comment by hkwu** [comment]
It's been a while (extremely busy around this time of year) but I've pushed these changes up. Install using

```bash
npm install ghastly@next
```

You can try it out, if it works well for you then I will release it under latest. As I finished making changes I realized that you actually need to provide a `RegExp` or the client won't know what the prefix is. The [docs](https://github.com/hkwu/ghastly/blob/custom-prefix/docs/guide.md#deferred-prefixes) have been updated to address the new additions.

**Comment by Dartv** [comment]
Thank you for taking your time. I'll try it out soon.
Btw, I really like the idea behind middleware. I actually heavily use your `applyMiddleware` function. I use it for things like meteor methods, publications and even graphql resolvers. Can you publish it as a separate package so we dont't have to install a whole package?

Example of graphql middleware:
```js
// checkLoggedIn
export default () => async (next, root, args, context) => {
  if (!context.userId) {
    throw new Error('Not logged in');
  }
  return next(root, args, context);
};
```
```js
export default applyMiddleware(
  flattenInput(),
  checkLoggedIn(),
  checkMembership(),
)(resolver);
```

You can even nest middleware:
```js
const middlewareC = () => async (next, root, args, context) => applyMiddleware(
  middlewareA(),
  middlewareB(),
)(next)(root, args, context);
```

**Comment by Dartv** [comment]
I'm now getting this error every time:
```
CommandParserError: Message does not contain enough words to specify a command.
    at Function.parse (C:\web\discordbot\node_modules\ghastly\lib\command\parsers\CommandParser.js:34:13)
    at Dispatcher.dispatch (C:\web\discordbot\node_modules\ghastly\lib\client\dispatcher\Dispatcher.js:170:47)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

To reproduce, simply use this:
```js
const client = new Client({
  prefix: message => message.guild && new RegExp('^\\?'),
});
```

**Comment by hkwu** [comment]
Glad you like it. I actually got the idea from web frameworks like Express and Laravel. Which function are you referring to? [These ones](https://github.com/hkwu/ghastly/blob/master/src/core/apply.js)? It's actually just a few lines, so I'm not sure if it's worth building a package out of 😂

Are you trying to match messages with an optional leading backslash? Seems like the `RegExp` is being parsed as `/^\?/` instead of `/^\\?/`. If I change it to `new RegExp('^\\\\?')` it works.

**Comment by Dartv** [comment]
No, I'm trying to make `?` a prefix. Because it's a special regex symbol, backslash is needed.

**Comment by hkwu** [comment]
Is the bot responding to the message? If so then that error is the bot trying to parse its own response (that's expected, since there's no explicit filter for bot messages).

**Comment by Dartv** [comment]
Yeah, it's responding. But the error is thrown only when I use function. It's a bit annoying.

**Comment by hkwu** [comment]
I see. Just pushed a change to filter out messages using function prefix properly.

**Comment by hkwu** [comment]
Merged the branch and closing this.
